// Test View types — Scene/UI と同列の「テスト」項目のドメインモデル。
//
// 詳細仕様は spec/rule/test-rules.md を参照。ここでは UI 上で扱う最小限の構造を定義する。

// ── Kinds ─────────────────────────────────────────────

/** テストの大分類。 */
export type TestKind = 'functional' | 'integration';

/** テストケースの実行結果。 */
export type TestStatus = 'pending' | 'running' | 'passed' | 'failed' | 'skipped';

/** テストモジュール（テストパーツ）のカテゴリ。 */
export type TestModuleCategory =
  | 'Movement'
  | 'Input'
  | 'UI'
  | 'Dialogue'
  | 'Battle'
  | 'Resource'
  | 'Custom';

/** Ergo での表現優先度。 */
export type ErgoPriority = 'high' | 'mid' | 'low';

// ── Entities ──────────────────────────────────────────

/** 機能テスト (Functional Test) — 1 コンポーネント / アクターの要件達成を確認する。 */
export interface FunctionalTest {
  id: string;
  /** `actor-name:component-name` の形式で記述する対象 */
  targetPath: string;
  /** 対応する codedesign の goal / テストケース記述 */
  requirement: string;
  /** 自動生成済みかどうか */
  generated: boolean;
  /** 依存するドライバー ID 配列 */
  driverIds: string[];
  /** 依存するテストモジュール ID 配列 */
  moduleIds: string[];
  /** 最後の実行結果 */
  lastStatus: TestStatus;
  /** 最後の実行で失敗した場合のメッセージ */
  lastMessage?: string;
}

/** 統合テスト (Integration Test) — シーン単位の操作フロー。 */
export interface IntegrationTest {
  id: string;
  /** 対象シーン ID */
  sceneId: string;
  /** フロー名 */
  name: string;
  /** AI が下書きした骨子（Markdown） */
  skeleton: string;
  /** 人間が書いた詳細（Markdown、再生成時も保持する） */
  details: string;
  /** 依存するテストモジュール ID 配列 */
  moduleIds: string[];
  /** 最後の実行結果 */
  lastStatus: TestStatus;
  lastMessage?: string;
}

/** テストドライバー — 要件を駆動する自動生成コードのメタ情報。 */
export interface TestDriver {
  id: string;
  /** 要件 / 機能を識別する名前 (kebab-case) */
  featureName: string;
  /** ドライバーの役割 */
  kind: 'input' | 'tick' | 'resource' | 'bus' | 'custom';
  /** 生成ファイルの相対パス (test/drivers/...) */
  filePath: string;
  /** 生成元となった要件 ID（トレーサビリティ用） */
  requirementId?: string;
  /** 自動生成か、手動調整済みか */
  autoGenerated: boolean;
}

/** テストモジュール (テストパーツ) — 再利用される操作の断片。 */
export interface TestModule {
  id: string;
  /** モジュール名 (例: MoveFreely) */
  name: string;
  category: TestModuleCategory;
  /** Ergo 表現の優先度 */
  ergoPriority: ErgoPriority;
  /** 対象コンポーネント（category/domain/name）配列 */
  targetComponents: string[];
  description: string;
  /** 同期元: 'project' は test/modules/、'registry' は Ars-TestModule リポジトリ */
  source: 'project' | 'registry';
  /** registry 同期の場合の出典リポジトリ (例: LUDIARS/Ars-TestModule) */
  registryRepo?: string;
}

// ── Helpers ───────────────────────────────────────────

export const TEST_KIND_LABEL: Record<TestKind, string> = {
  functional: '機能テスト',
  integration: '統合テスト',
};

export const TEST_STATUS_LABEL: Record<TestStatus, string> = {
  pending: '未実行',
  running: '実行中',
  passed: '成功',
  failed: '失敗',
  skipped: 'スキップ',
};

export const TEST_STATUS_COLOR: Record<TestStatus, string> = {
  pending: 'var(--text-muted)',
  running: 'var(--accent)',
  passed: 'var(--green)',
  failed: 'var(--red)',
  skipped: 'var(--text-muted)',
};

export const MODULE_CATEGORY_ORDER: TestModuleCategory[] = [
  'Movement',
  'Input',
  'UI',
  'Dialogue',
  'Battle',
  'Resource',
  'Custom',
];

/** 統合テストのデフォルト骨子テンプレート（AI 生成前の雛形）。 */
export const DEFAULT_INTEGRATION_SKELETON = `## 初期化
- シーンを起動する
- 必要な入力ドライバーを接続する

## 操作
- （テストモジュールを列挙）

## 検証
- 期待される状態変化を確認する

## クリーンアップ
- シーンを閉じる
`;

/** 統合テスト詳細（人間記述）領域のデフォルトヘッダ。 */
export const DEFAULT_INTEGRATION_DETAILS = `## 詳細 (人間が記述)
<!-- 骨子で列挙されたステップの具体的な条件・期待値・待機ポイントを書き足してください。
     このセクションは骨子の再生成時も保持されます。 -->
`;
